### ISSUE TITLE
colon in text in forms breaks inport in gvSig

### ISSUE THREAD

**Issue by tghoward** [moovida/hydrologis4gvsig#11] opened 2018-05-10 16:41 UTC
If a geopaparazzi form has a colon in a text name, such as

"sectionname": "test: survey",

or, if a form has a colon in a value, it validates on jsonlint (and saves in geopap), but the gvSig import breaks. 

I'm attaching a json form that shows this behavoir.   Perhaps this is a geopaparazzi thing?
[tags_colonExample.txt](https://github.com/TheHortonMachine/hydrologis4gvsig/files/1992450/tags_colonExample.txt)

To test in Geopaparazzi, change the file name to tags.json and place in geopaparazzi folder on phone. 

After filling out the form, try uploading in gvSig using the plug in. 

Tim

**Comment by moovida** [comment] 2018-05-12 12:19
This is indeed in the Hortonmachine part. The problem is only on windows, where the colon is not allowed in the filename. The form shpfiles contain the form name. 

This has been fixed in teh hortonmachine lib: https://github.com/TheHortonMachine/hortonmachine/commit/0d982238e07f4553e5153672c0b1a97885c18c88

**Closed as completed by moovida** 2018-05-12 12:19 UTC
Labels: bug
